rooms:
  - name: Living Room
    type: liveable
    zones:
      - name: Zone 1
        devices:
          - name: Heater 1
            type: heater
          - name: Heater 2
            type: heater
        sensors:
          - name: Temperature Sensor 1
            type: temperature_sensor
      - name: Zone 2
        devices:
          - name: LED Light 1
            type: led_light
  - name: Greenhouse
    type: greenhouse
    zones:
      - name: Zone 1
        devices:
          - name: Fertilizer 1
            type: fertilizer
          - name: Humidifier 1
            type: humidifier
          - name: IrrigationSystem 1
            type: irrigation_system
        sensors:
          - name: Fertilizer Sensor 1
            type: fertilization_sensor
          - name: Fertilizer Sensor 2
            type: fertilization_sensor
          - name: Fertilizer Sensor 3
            type: fertilization_sensor
          - name: Humidity Sensor 1
            type: humidity_sensor
          - name: Irrigation Sensor 1
            type: irrigation_sensor

