rooms:
  - name: Greenhouse
    type: greenhouse
    zones:
      - name: Zone 1
        devices:
          - name: Fertilizer 1
            type: fertilizer
        sensors:
          - name: Fertilizer Sensor 1
            type: fertilization_sensor

